version: '3.8'

services:
  db:
    build: 
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: goal_tracker_db
    ports:
      - "3306:3306"

  backend:
    build: 
      context: ./server
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: goal_tracker_db
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: 
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
